alias: Ohmonhass Nordpool
description: ""
trigger:
  - platform: time_pattern
    minutes: /4
    id: Billigare
condition: []
action:
  - service: number.set_value
    entity_id: number.ohmonwifihass_temperature
    data_template:
      value: "{{ states('sensor.gw2000a_outdoor_temperature') | float }}"
mode: single
